FROM node:13.12.0-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# A wildcard is used to ensure both package.json AND
# package-lock.json are copied
COPY package*.json ./

## Install only the packages defined in the package-lock.json (faster than normal npm install)
RUN npm install

# Add app by copying the contents of the project to the image
COPY . ./

# Run 'npm start' when the container starts
CMD ["npm", "start"]