services:
    - docker

before_install:
    - docker build -t agagnon227/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true agagnon227/react-test npm run test -- --coverage

after_success:
    - docker build -t agagnon227/multi-client ./client
    - docker build -t agagnon227/multi-nging ./nginx
    - docker build -t agagnon227/multi-api ./server
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push agagnon227/multi-client
    - docker push agagnon227/multi-nginx
    - docker push agagnon227/multi-api