version: "3"
services:
    nginx:
        image: agagnon227/multi-nginx
        container_name: nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - "8080:80"
    api:
        image: agagnon227/multi-api
        container_name: api
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./server:/app
    client:
        image: agagnon227/multi-client
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        
