version: '3'
services:
    client:
        image: agagnon227/portfolio-client
        container_name: client
        build:
            context: client
            dockerfile: Dockerfile.dev
        volumes:
            - './client:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
################################
#   Setup node container
################################
#     server:
#         build:
#             context: ./server
#             dockerfile: Dockerfile.dev
#         environment:
#             API_HOST: ${API_HOST}
#             APP_SERVER_PORT: ${APP_SERVER_PORT}
#         expose:
#             - ${APP_SERVER_PORT}
#         ports:
#             - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
#         volumes:
#             - /app/node_modules
#             - ./server:/app
#         restart: on-failure
#         image: agagnon227/portfolio-server
#         container_name: portfolio-server
# ################################
# #   Setup client container
# ################################
#     client:
#         build:
#             context: ./client
#             dockerfile: Dockerfile.dev
#         environment: 
#             - REACT_APP_PORT=${REACT_APP_PORT}
#         expose:
#             - ${REACT_APP_PORT}
#         ports:
#             - '${REACT_APP_PORT}:${REACT_APP_PORT}'
#         volumes:
#             - /app/node_modules
#             - ./client:/app
#         links: 
#             - server
#         restart: on-failure
#         image: agagnon227/portfolio-client
#         container_name: portfolio-client