version: '3'
services:
################################
#   Setup node container
################################
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        environment:
            API_HOST: ${API_HOST}
            APP_SERVER_PORT: ${APP_SERVER_PORT}
        expose:
            - ${APP_SERVER_PORT}
        ports:
            - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
        volumes:
            - /app/node_modules
            - ./server:/app
        restart: on-failure
        container_name: server
################################
#   Setup client container
################################
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        environment: 
            - REACT_APP_PORT=${REACT_APP_PORT}
        expose:
            - ${REACT_APP_PORT}
        ports:
            - '${REACT_APP_PORT}:${REACT_APP_PORT}'
        volumes:
            - /app/node_modules
            - ./client:/app
        links: 
            - server
        restart: on-failure
        container_name: client