version: '3'
services:
    web-app:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - '3000:3000'
        restart: on-failure
        container_name: web-app
    portfolio-api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        ports:
            - '3001:3001'
        restart: on-failure
        container_name: portfolio-api
        volumes:
            - /app/node_modules
            - ./server:/app